name: Build ANTLR Parser

on:
  push:
    branches: [main]

permissions:
  contents: write  # 💡 This is required to allow git push

jobs:
  build-antlr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create directories
        run: |
          mkdir -p lib src/generated bin

      - name: Download ANTLR jar
        run: |
          curl -L -o lib/antlr-4.9.2-complete.jar https://www.antlr.org/download/antlr-4.9.2-complete.jar

      - name: Generate ANTLR parser
        run: |
          java -jar lib/antlr-4.9.2-complete.jar -Dlanguage=Java -o src/generated -package danex.antlr src/grammar/Danex*.g4

      - name: Compile ANTLR-generated Java files
        run: |
          javac -cp lib/antlr-4.9.2-complete.jar -d bin src/generated/*.java

      - name: Package to JAR (optional)
        run: |
          jar cf danex-parser.jar -C bin .
          mkdir -p dist
          mv danex-parser.jar dist/

      - name: Upload JAR as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: danex-parser
          path: dist/danex-parser.jar
