name: Build ANTLR Parser

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-antlr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create directories
        run: |
          mkdir -p lib src/generated bin

      - name: Download ANTLR jar
        run: |
          curl -L -o lib/antlr-4.9.2-complete.jar https://www.antlr.org/download/antlr-4.9.2-complete.jar

      - name: Generate ANTLR Lexer
        run: |
          java -jar lib/antlr-4.9.2-complete.jar \
            -Dlanguage=Java \
            -o src/generated \
            -package danex.antlr \
            grammar/DanexLexer.g4

      - name: Debug generated files for lexer
        run: |
          echo "Listing src/generated directory after lexer generation:"
          find src/generated -maxdepth 2 -type f | sed 's/^/  /'

      - name: Copy .tokens file to output dir
        run: |
          if [ -f src/generated/grammar/DanexLexer.tokens ]; then
            echo "Found tokens at src/generated/grammar/DanexLexer.tokens, copying to src/generated/"
            cp src/generated/grammar/DanexLexer.tokens src/generated/
          else
            echo "ERROR: DanexLexer.tokens not found at expected location!"
            exit 1
          fi

      - name: Generate ANTLR Parser
        run: |
          java -jar lib/antlr-4.9.2-complete.jar \
            -Dlanguage=Java \
            -o src/generated \
            -package danex.antlr \
            -lib src/generated \
            grammar/DanexParser.g4

      - name: Compile ANTLR-generated Java files
        run: |
          find src/generated -name "*.java" > sources.txt
          javac -cp lib/antlr-4.9.2-complete.jar -d bin @sources.txt

      - name: Package to JAR (optional)
        run: |
          jar cf danex-parser.jar -C bin .
          mkdir -p dist
          mv danex-parser.jar dist/

      - name: Upload JAR as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: danex-parser
          path: dist/danex-parser.jar
