name: Fetch ANTLR Jar

on:
  push:
    branches: [ main ]

jobs:
  download-antlr:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 💡 This is required to allow git push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create lib directory
        run: mkdir -p lib

      - name: Download ANTLR jar
        run: curl -L -o lib/antlr-4.9.2-complete.jar https://www.antlr.org/download/antlr-4.9.2-complete.jar

      - name: Commit and push ANTLR jar
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add lib/antlr-4.9.2-complete.jar
          git commit -m "Add ANTLR jar via GitHub Actions" || echo "Nothing to commit"
          git push
