name: Fetch ANTLR Jar

on:
  push:
    branches: [ main ]  # or change to your default branch name

jobs:
  download-antlr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create lib directory
        run: mkdir -p lib

      - name: Download ANTLR jar
        run: curl -L -o lib/antlr-4.9.2-complete.jar https://www.antlr.org/download/antlr-4.9.2-complete.jar

      - name: Commit jar file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add lib/antlr-4.9.2-complete.jar
          git commit -m "Add ANTLR jar via GitHub Actions"
          git push
