name: Generate AstBuilder

on:
  push:
    # Trigger when generator or AST classes change
    paths:
      - 'tools/AstBuilderGenerator.java'
      - 'src/danex/ast/**'
      - '.github/workflows/gen-astbuilder.yml'
    branches: [main]

permissions:
  contents: write

jobs:
  generate-astbuilder:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout with full history for rebase/push
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Set up Java 17
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Ensure directories exist
      - name: Ensure directories exist
        run: |
          mkdir -p src/danex
          mkdir -p bin

      # 4. Skip if AstBuilder.java already exists
      - name: Skip if AstBuilder.java exists
        run: |
          if [ -f src/danex/AstBuilder.java ]; then
            echo "✅ src/danex/AstBuilder.java already exists. Skipping generation."
            exit 0
          fi
          echo "⚠️ src/danex/AstBuilder.java not found. Proceeding to generate."

      # 5. Compile AstBuilderGenerator (no external deps needed)
      - name: Compile AstBuilderGenerator
        run: |
          javac -d bin tools/AstBuilderGenerator.java

      # 6. Run the generator
      - name: Run AstBuilderGenerator
        run: |
          java -cp bin tools.AstBuilderGenerator

      # 7. Debug: list contents under src/danex to confirm file creation
      - name: Debug - list src/danex contents
        run: |
          echo "Contents of src/danex/:"
          ls -R src/danex || echo "src/danex/ not found"

      # 8. Confirm AstBuilder.java exists and show top lines
      - name: Confirm AstBuilder.java exists
        run: |
          if [ -f src/danex/AstBuilder.java ]; then
            echo "✅ src/danex/AstBuilder.java was generated"
            head -n 20 src/danex/AstBuilder.java
          else
            echo "❌ src/danex/AstBuilder.java NOT found; generator may have failed"
            exit 1
          fi

      # 9. Compile AST classes first
      - name: Compile AST classes
        run: |
          javac -d bin src/danex/ast/*.java

      # 10. Compile generated AstBuilder to catch compile errors
      - name: Compile generated AstBuilder
        run: |
          javac -cp "bin" -d bin src/danex/AstBuilder.java

      # 11. Commit generated AstBuilder.java if changed, with pull--rebase
      - name: Commit generated AstBuilder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add src/danex/AstBuilder.java

          # If no differences, skip
          if git diff --cached --quiet; then
            echo "No AstBuilder changes to commit."
            exit 0
          fi

          # Rebase onto latest to avoid push conflicts
          git fetch origin main
          git rebase origin/main

          git commit -m "chore: regenerate AstBuilder.java [skip ci]"

          # Push with retry logic
          max_attempts=3
          attempt=1
          until git push origin HEAD:main; do
            if [ $attempt -ge $max_attempts ]; then
              echo "❌ Push failed after $attempt attempts."
              exit 1
            fi
            echo "⚠️ Push failed. Retrying ($attempt/$max_attempts)..."
            git pull --rebase origin main
            attempt=$((attempt + 1))
          done
