name: Generate AstBuilder

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-astbuilder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Ensure src/danex directory exists
        run: mkdir -p src/danex

      - name: Compile AstBuilderGenerator
        run: |
          mkdir -p bin
          javac -d bin tools/AstBuilderGenerator.java

      - name: Run AstBuilderGenerator
        run: |
          java -cp bin tools.AstBuilderGenerator

      - name: Debug: list src/danex contents
        run: |
          echo "Contents of src/danex/:"
          ls -R src/danex || echo "src/danex/ not found"

      - name: Compile generated AstBuilder
        run: |
          mkdir -p bin
          javac -cp "lib/antlr-4.9.2-complete.jar:lib/danex-parser.jar" -d bin src/danex/AstBuilder.java || exit 1

      - name: Commit generated AstBuilder
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add src/danex/AstBuilder.java
          git commit -m "chore: Generate AstBuilder.java [skip ci]" || echo "No changes to commit"
          git push

      - name: Cleanup workflow (optional self-delete)
        run: |
          rm .github/workflows/gen-astbuilder.yml
          git add .github/workflows/gen-astbuilder.yml
          git commit -m "chore: Remove self after generating AstBuilder [skip ci]" || echo "Nothing to commit"
          git push || echo "Nothing to push"
