name: Generate Interpreter

on:
  push:
    paths:
      - 'src/danex/ast/**'             # if your AST classes changed
      - 'tools/InterpreterTemplateGenerator.java'
      - '.github/workflows/generate-interpreter.yml'
    branches: [main]

permissions:
  contents: write

jobs:
  generate-interpreter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Ensure output directory exists
        run: mkdir -p src/danex

      - name: Download ANTLR runtime if missing
        run: |
          mkdir -p lib
          if [ ! -f lib/antlr-4.9.2-complete.jar ]; then
            curl -L -o lib/antlr-4.9.2-complete.jar https://www.antlr.org/download/antlr-4.9.2-complete.jar
          fi

      - name: Ensure parser JAR exists
        run: |
          if [ ! -f lib/danex-parser.jar ]; then
            echo "❌ lib/danex-parser.jar not found. Ensure parser build ran first."
            exit 1
          fi

      - name: Compile InterpreterTemplateGenerator
        run: |
          mkdir -p bin
          javac -cp "lib/danex-parser.jar:lib/antlr-4.9.2-complete.jar" -d bin tools/InterpreterTemplateGenerator.java

      - name: Run InterpreterTemplateGenerator
        run: |
          java -cp "bin:lib/danex-parser.jar:lib/antlr-4.9.2-complete.jar" tools.InterpreterTemplateGenerator

      - name: Show generated Interpreter.java
        run: |
          echo "Contents of src/danex/Interpreter.java:"
          sed -n '1,200p' src/danex/Interpreter.java
          echo "..."

      - name: Commit generated Interpreter if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git rebase origin/main
          git add src/danex/Interpreter.java
          if git diff --cached --quiet; then
            echo "No Interpreter changes to commit."
          else
            git commit -m "chore: regenerate Interpreter skeleton [skip ci]"
            git push origin HEAD:main
          fi
