name: Run DanexLang Example

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache ANTLR runtime JAR
        uses: actions/cache@v3
        with:
          path: lib/antlr-4.9.2-complete.jar
          key: antlr-runtime-v4.9.2

      - name: Ensure ANTLR runtime JAR present
        run: |
          mkdir -p lib
          if [ ! -f lib/antlr-4.9.2-complete.jar ]; then
            curl -L -o lib/antlr-4.9.2-complete.jar https://www.antlr.org/download/antlr-4.9.2-complete.jar
          fi

      - name: Generate ANTLR Lexer & Parser (with visitors)
        run: |
          mkdir -p src/danex

          echo "Generating lexer..."
          java -jar lib/antlr-4.9.2-complete.jar \
            -Dlanguage=Java \
            -visitor \
            -package danex.grammar \
            -o src/danex \
            grammar/DanexLexer.g4

          echo "Locating .tokens file..."
          TOKENS_DIR=$(find src/danex/grammar -name DanexLexer.tokens -exec dirname {} \;)
          echo "Found tokens in: $TOKENS_DIR"

          echo "Generating parser..."
          java -jar lib/antlr-4.9.2-complete.jar \
            -Dlanguage=Java \
            -visitor \
            -package danex.grammar \
            -o src/danex \
            -lib "$TOKENS_DIR" \
            grammar/DanexParser.g4

      - name: Compile all source files
        run: |
          mkdir -p bin
          echo "Compiling ANTLR-generated files..."
          find src/danex/grammar -name "*.java" > gen-sources.txt
          javac -cp lib/antlr-4.9.2-complete.jar -d bin @gen-sources.txt

          echo "Compiling DanexLang source..."
          find src -name "*.java" > sources.txt
          javac -cp "lib/antlr-4.9.2-complete.jar:bin" -d bin @sources.txt

      - name: Run DanexLang example
        run: |
          java -cp "bin:lib/antlr-4.9.2-complete.jar" danex.Main example/IsEven.danex
